welcome:
    path: /
    controller: App\Controller\WelcomeController::index
companies:
    path: /companies
    controller: App\Controller\Web\CompanyController::index
add_company:
    path: /addcompany
    controller: App\Controller\Web\CompanyController::add
view_company:
    path: /viewcompany/{id}
    controller: App\Controller\Web\CompanyController::view
    defaults:
            id: 1
view_all_companies:
    path: /viewallcompanies
    controller: App\Controller\Web\CompanyController::viewAll
delete_company:
    path: /deletecompany/{id}
    controller: App\Controller\Web\CompanyController::delete
    defaults:
            id: 1
update_company_first:
    path: /updatecompanyfirst/{id}
    controller: App\Controller\Web\CompanyController::updateFirst
    defaults:
            id: 1
update_company_second:
    path: /updatecompanysecond/{id}
    controller: App\Controller\Web\CompanyController::updateSecond
    defaults:
            id: 1
stations:
    path: /stations
    controller: App\Controller\Web\StationController::index
add_station:
    path: /addstation
    controller: App\Controller\Web\StationController::add
view_station:
    path: /viewstation/{id}
    controller: App\Controller\Web\StationController::view
    defaults:
            id: 1
view_all_stations:
    path: /viewallstations
    controller: App\Controller\Web\StationController::viewAll
delete_station:
    path: /deletestation/{id}
    controller: App\Controller\Web\StationController::delete
    defaults:
            id: 1
update_station_first:
    path: /updatestation/{id}
    controller: App\Controller\Web\StationController::updateFirst
    defaults:
            id: 1
update_station_second:
  path: /updatestationsecond/{id}
  controller: App\Controller\Web\StationController::updateSecond
  defaults:
          id: 1
view_all_stations_by_distance:
    path: /viewdistance
    controller: App\Controller\Web\StationController::viewDistance
view_all_stations_by_company_id:
    path: /viewtree
    controller: App\Controller\Web\StationController::viewTree